### ISSUE TITLE
stop-slave Broken on MySQL 5.7.8+

### ISSUE THREAD

**Issue by jacripe** [holland-backup/holland#185]
The "stop-slave" option available in the mysqldump backupset configuration does not work with the default behaviour on MySQL 5.7.8+. The MySQL community release has changed the default setting of the show_compatibility_56 variable from ON to OFF in the 5.7.7 to 5.7.8 release, https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_show_compatibility_56_slave_status . Having this variable disabled removes the "Slave_running" and similar status variables. As a result, Holland fails when attempting to perform the pre-backup slave sanity checks.

SAMPLE ERROR:
```
~ # mysql -e 'show global variables like "show_compatibility_56" \G'
*************************** 1. row ***************************
Variable_name: show_compatibility_56
        Value: OFF

~ # mysql -e 'show slave status\G'
*************************** 1. row ***************************
               Slave_IO_State: Waiting for master to send event
...
             Slave_IO_Running: Yes
            Slave_SQL_Running: Yes
...

~ # grep stop-slave /etc/holland/backupsets/default.conf 
stop-slave = yes

~ # holland bk
Holland 1.0.14 started with pid 7055
--- Starting backup run ---
Creating backup path /var/spool/holland/default/20180314_123929
Estimating size of mysqldump backup
Estimated Backup Size: 144.95MB
Starting backup[default/20180314_123929] via plugin mysqldump
Backup failed after 0.05 seconds
Purged failed backup: default/20180314_123929
Released lock /etc/holland/backupsets/default.conf
Uncaught exception while running command 'bk': TypeError("'NoneType' object is not iterable",)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/holland/core/command/command.py", line 209, in dispatch
    return self.run(self.optparser.prog, opts, *args)
  File "/usr/lib/python2.7/site-packages/holland/commands/backup.py", line 103, in run
    runner.backup(name, config, opts.dry_run)
  File "/usr/lib/python2.7/site-packages/holland/core/backup/base.py", line 124, in backup
    plugin.backup()
  File "/usr/lib/python2.7/site-packages/holland/backup/mysqldump/plugin.py", line 171, in backup
    if self.client.show_status('Slave_running', session=None) != 'ON':
  File "/usr/lib/python2.7/site-packages/holland/lib/mysql/client/base.py", line 383, in show_status
    key, value = cursor.fetchone()
TypeError: 'NoneType' object is not iterable

```
HOLLAND RELEASE, 1.0.4+
https://github.com/holland-backup/holland/commit/c6d6d64af6fa90c836c7aeae8c51256207ec6895#diff-db46cb2c38fc7c110c0fadae1ba56cc8

RELEVANT CODE:
```
/usr/lib/python2.7/site-packages/holland/backup/mysqldump/plugin.py
    155     def backup(self):
    156         """Run a MySQL backup"""
...
    168         try:
    169             if self.config['mysqldump']['stop-slave']:
    170                 self.client = connect(self.mysql_config['client'])
    171                 if self.client.show_status('Slave_running', session=None) != 'ON':
    172                     raise BackupError("stop-slave enabled, but replication is "
    173                                   "either not configured or the slave is not "
    174                                   "running.")
    175                 self.config.setdefault('mysql:replication', {})
    176                 _stop_slave(self.client, self.config['mysql:replication'])
    177             self._backup()
...

/usr/lib/python2.7/site-packages/holland/lib/mysql/client/base.py
    373     def show_status(self, key, session=False):
    374         """Fetch MySQL server status"""
    375         if session is not None:
    376             scope = self.SCOPE[session]
    377         else:
    378             # 4.1 support - GLOBAL/SESSION STATUS is not implemented
    379             scope = ''
    380         sql = 'SHOW %s STATUS LIKE ' % scope + '%s'
    381         cursor = self.cursor()
    382         cursor.execute(sql, (key,))
    383         key, value = cursor.fetchone()
    384         cursor.close()
    385         return value
```

**Comment by soulen3** [comment]
This should be fixed in https://github.com/holland-backup/holland/releases/tag/v1.1.0.

Thanks,
Steve
