### ISSUE TITLE
TypeError: write() argument 1 must be unicode, not str

### ISSUE THREAD

**Issue by PJRO** [holland-backup/holland#207]
I am currently trying to get Holland working on Ubuntu but I get the following error when running `holland bk`

```
Uncaught exception while running command 'bk': TypeError('write() argument 1 must be unicode, not str',)

Traceback (most recent call last):
File "build/bdist.linux-x86_64/egg/holland/core/command/command.py", line 210, in dispatch     return self.run(self.optparser.prog, opts, *args)
File "build/bdist.linux-x86_64/egg/holland/commands/backup.py", line 103, in run     runner.backup(name, config, opts.dry_run)
File "build/bdist.linux-x86_64/egg/holland/core/backup/base.py", line 124, in backup     plugin.backup()
File "/usr/lib/python2.7/dist-packages/holland/backup/mysqldump/plugin.py", line 177, in backup     self._backup()
File "/usr/lib/python2.7/dist-packages/holland/backup/mysqldump/plugin.py", line 241, in _backup     compression_ext=ext)
File "/usr/lib/python2.7/dist-packages/holland/backup/mysqldump/base.py", line 48, in start     write_manifest(schema, open_stream, compression_ext)
File "/usr/lib/python2.7/dist-packages/holland/backup/mysqldump/base.py", line 109, in write_manifest     manifest.writerow([name.encode('utf-8'), encoded_name + '.sql' + ext])

TypeError: write() argument 1 must be unicode, not str
```
I'm not too sure what could be causing this.

Other Info:
Ubuntu Version: 16.04
Holland Version: 1.1.0
Mysql Version: 5.7.11
Python Version: 2.7.12

**Comment by soulen3** [comment]
It looks like you're running an old version of the mysqldump backup plugin.  Please make sure holland.backup.mysqldump, holland.lib.mysql, and holland.lib.common have been update.

You can check the version using the list-plugin(lp) flag.
```
# holland lp
Holland 1.1.5 started with pid 6973
Plugin-Type  Plugin-Name     Version   Author           Summary
--------------------------------------------------------------------------------
backup       mysqldump       1.1.5dev-r0 Rackspace        MySQLDump Backup/Restore Plugins
command      backup          1.1.5     Rackspace        Holland Core Plugins
command      listbackups     1.1.5     Rackspace        Holland Core Plugins
command      listplugins     1.1.5     Rackspace        Holland Core Plugins
command      mk-config       1.1.5     Rackspace        Holland Core Plugins
command      purge           1.1.5     Rackspace        Holland Core Plugins
```

Please see https://github.com/holland-backup/holland/blob/master/INSTALL for details on install plugins.

**Comment by PJRO** [comment]
I get the following: 
```
Holland 1.1.0 started with pid 5393
Plugin-Type  Plugin-Name     Version   Author           Summary
--------------------------------------------------------------------------------
backup       mysqldump       1.0.14dev-r0 Rackspace        MySQLDump Backup/Rest                                                                                                                                                             ore Plugins
backup       xtrabackup      1.1.0dev-r0 Rackspace        Holland plugin for Per                                                                                                                                                             cona XtraBackup
command      backup          1.1.0     Rackspace        Holland Core Plugins
command      help            1.1.0     Rackspace        Holland Core Plugins
command      listbackups     1.1.0     Rackspace        Holland Core Plugins
command      listplugins     1.1.0     Rackspace        Holland Core Plugins
command      mk-config       1.1.0     Rackspace        Holland Core Plugins
command      purge           1.1.0     Rackspace        Holland Core Plugins
```

When running apt-get update it tells me that holland is already using the newest version (Which must be wrong considering your comment shows 1.1.5.

Although I would have thought it everything on my machine is using 1.1.0 they should all work nicely together.

**Comment by soulen3** [comment]
I haven't a lot of success building packages for Ubuntu.   You could try installing it from source or using the packages provided here: https://download.opensuse.org/repositories/home:/holland-backup/xUbuntu_18.04/
