### ISSUE TITLE
mysql-lvm provider config is missing the `inline` option in 1.1.5+

### ISSUE THREAD

**Issue by prwhitaker** [holland-backup/holland#212]
The config file for the mysql-lvm provider is missing the `inline` option from the `[compression]` section.
That causes the following error with any attempt to use that provide (dry-run or full backup):

```
# holland bk --dry-run
Holland 1.1.7 started with pid 3531
--- Starting dry run ---
Creating backup path /mnt/mysqlbackups/mysql-lvm/20181006_071313
Estimated Backup Size: 21.50GB
Using Historic Space Estimate: Checking for information in /mnt/mysqlbackups/mysql-lvm/newest/backup.conf
Last backup used 5.55GB
The new backup estimate is at least 1.5 times the size of the currnet estimate: 21.50GB > (0.00B * 1.5). Default back to 'estimated-size-factor'
Adjusting estimated size by 0.30 to 6.45GB
Starting backup[mysql-lvm/20181006_071313] via plugin mysql-lvm
Backing up /mnt/mysql-lvm/mysql via snapshot
/usr/lib/python2.6/site-packages/holland/lib/lvm/base.py:23: DeprecationWarning: object.__new__() takes no parameters
  return super(Volume, cls).__new__(cls, attributes)
Auto-sizing snapshot-size to 15.00GB (3840 extents)
'inline'
Uncaught exception while running command 'holland backup': KeyError('inline',)
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/holland/core/command/command.py", line 110, in dispatch
    return self.run(self.optparser.prog, opts, *args)
  File "/usr/lib/python2.6/site-packages/holland/commands/backup.py", line 117, in run
    runner.backup(name, config, opts.dry_run)
  File "/usr/lib/python2.6/site-packages/holland/core/backup/base.py", line 153, in backup
    plugin.backup()
  File "/usr/lib/python2.6/site-packages/holland/backup/mysql_lvm/plugin/raw/plugin.py", line 147, in backup
    spooldir=self.target_directory)
  File "/usr/lib/python2.6/site-packages/holland/backup/mysql_lvm/plugin/raw/util.py", line 74, in setup_actions
    inline=config['compression']['inline'])
  File "/usr/lib/python2.6/site-packages/configobj.py", line 583, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'inline'
```

Adding `inline = 1` to that section:
```
[compression]
inline = 1
method = gzip
level = 1
```
allows the backups to succeed

**Comment by soulen3** [comment]
Looks like the `inline` option is missing here: https://github.com/holland-backup/holland/blob/master/plugins/holland.backup.mysql_lvm/holland/backup/mysql_lvm/plugin/raw/plugin.py#L55-L59

Thanks for reporting this
