### ISSUE TITLE
Holland Commvault setuptools bug on Python 2.6

### ISSUE THREAD

**Issue by soulen3** [holland-backup/holland#252]
Holland (commvault agent) 1.1.8 started with pid 32679
Traceback (most recent call last):
  File "/usr/sbin/holland_cvmysqlsv", line 9, in <module>
    load_entry_point('holland-commvault==1.1.8', 'console_scripts', 'holland_cvmysqlsv')()
  File "/usr/lib/python2.6/site-packages/holland_commvault/commvault.py", line 97, in main
    if run(args, largs):
  File "/usr/lib/python2.6/site-packages/holland/core/command/__init__.py", line 40, in run
    commands = get_commands()
  File "/usr/lib/python2.6/site-packages/holland/core/plugin.py", line 84, in get_commands
    cmdcls = entry_point.load()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1947, in load
    if require: self.require(env, installer)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1960, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 550, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (setuptools 0.6c11 (/usr/lib/python2.6/site-packages), Requirement.parse('setuptools>=0.7'))

**Comment by soulen3** [comment]
Confirmed this is a problem with the version of setuptools that was install locally via pip.
