### ISSUE TITLE
holland_cvmysqlsv issue in 1.1.12

### ISSUE THREAD

**Issue by soulen3** [holland-backup/holland#276]
`holland_cvmysqlsv` will error out if the `--bkset` argument isn't defined

```
Holland (commvault agent) 1.1.12 started with pid 56924
Traceback (most recent call last):
  File "/sbin/holland_cvmysqlsv", line 9, in <module>
    load_entry_point('holland-commvault==1.1.12', 'console_scripts', 'holland_cvmysqlsv')()
  File "/usr/lib/python2.7/site-packages/holland_commvault/commvault.py", line 109, in main
    status_file = '%s/%s/newest/job_%s' % (spool, args.bksets[0], args.job)
IndexError: list index out of range
```

**Comment by soulen3** [comment]
Should be fixed as of 1.1.13
