### ISSUE TITLE
Holland can't parse config file

### ISSUE THREAD

**Issue by tomldickson** [holland-backup/holland#283]
On CentOS 6.10, holland has stopped working with this error:
```
root@mysql.production (.91) /etc/holland/backupsets # /usr/sbin/holland  bk
Configuration error holland.backupsets: the value "default" is of the wrong type.
Configuration error holland.plugin-dirs: the value "/usr/share/holland/plugins" is of the wrong type.
Traceback (most recent call last):
  File "/usr/sbin/holland", line 9, in <module>
    load_entry_point('holland==1.1.13', 'console_scripts', 'holland')()
  File "/usr/lib/python2.6/site-packages/holland/core/cmdshell.py", line 37, in main
    bootstrap(opts)
  File "/usr/lib/python2.6/site-packages/holland/core/util/bootstrap.py", line 90, in bootstrap
    setup_config(opts)
  File "/usr/lib/python2.6/site-packages/holland/core/util/bootstrap.py", line 26, in setup_config
    _setup_config(opts.config_file)
  File "/usr/lib/python2.6/site-packages/holland/core/config/config.py", line 224, in setup_config
    HOLLANDCFG.validate_config(CONFIGSPEC)
  File "/usr/lib/python2.6/site-packages/holland/core/config/config.py", line 100, in validate_config
    "Configuration errors were encountered while validating %r" % self.filename
holland.core.config.config.ConfigError: Configuration errors were encountered while validating '/etc/holland/holland.conf'
```

However, /etc/holland/holland.conf seems correct (will try to attach).

**Comment by tomldickson** [comment]
I don't see how to attach a file, so here's a paste (markdown is going to go insane):

`## Root holland config file
[holland]

## Paths where holland plugins may be found.
## Can be comma separated
plugin_dirs = /usr/share/holland/plugins

## Top level directory where backups are held
backup_directory = /var/lib/mysqlbackup

## List of enabled backup sets. Can be comma separated. 
## Read from <config_dir>/backupsets/<name>.conf
# backupsets = example, traditional, parallel_backups, non_transactional
backupsets = default

# Define a umask for file generated by holland
umask = 0007

# Define a path for holland and its spawned processes
path = /usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin

[logging]
## where to write the log
filename = /var/log/holland/holland.log

## debug, info, warning, error, critical (case insensitive)
level = info

## Log format using python logging module format
format = '%(asctime)s PID-%(process)s [%(levelname)s] %(message)s'`

**Comment by soulen3** [comment]
Thanks for reporting this.  I've edited your posts to fix the markdown formatting.  (You can create block using ``` )

I'm having trouble reproducing this.  Did you install holland from epel? Was it working before updating to 1.1.13?

**Comment by tomldickson** [comment]
Thanks for the quick reply and the edits - I'm on a CentOS server on Rackspace - and I just noticed it stopped working (appears to be sometime around October based on the file dates in /var/lib/mysqlbackup).

```
root@mysql.production (.91) /etc/holland/backupsets # yum list holland
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
drivesrvr                                                                                                                                                              | 2.9 kB     00:00     
Installed Packages
holland.noarch                                                                               1.1.13-1.el6                                                                                @epel
```

```
root@mysql.production (.91) /etc/holland/backupsets # ls /var/lib/mysqlbackup/default/ -lart
total 36
drwxr-xr-x 3 root root 4096 Mar 21  2014 ..
drwxrwx--- 3 root root 4096 Sep 26  2018 20180926_035401
drwxrwx--- 3 root root 4096 Sep 27  2018 20180927_035401
drwxrwx--- 3 root root 4096 Sep 28  2018 20180928_035402
drwxrwx--- 3 root root 4096 Sep 29  2018 20180929_035401
drwxrwx--- 3 root root 4096 Sep 30  2018 20180930_035401
drwxrwx--- 3 root root 4096 Oct  1  2018 20181001_035401
drwxrwx--- 3 root root 4096 Oct  2  2018 20181002_035401
lrwxrwxrwx 1 root root   44 Oct  2  2018 oldest -> /var/lib/mysqlbackup/default/20180926_035401
lrwxrwxrwx 1 root root   44 Oct  2  2018 newest -> /var/lib/mysqlbackup/default/20181002_035401
drwxrwx--- 9 root root 4096 Oct  2  2018 .
```

Looks like that may have been around the time an update happened:

```
root@mysql.production (.91) /etc/holland/backupsets # yum history info holland
Loaded plugins: fastestmirror
Transaction ID : 458
Begin time     : Fri Mar 29 03:45:29 2019
Begin rpmdb    : 425:3d2f6081b97fd37ee28a144f55c2f6f922d4b523
End time       :            03:45:30 2019 (1 seconds)
End rpmdb      : 425:830b15761ee69e238f87455523de60e86e2eab5b
User           : root <root>
Return-Code    : Success
Command Line   : -e 0 -d 0 -y shell /etc/yum/yum-daily.yum
Additional non-default information stored: 1
Transaction performed with:
    Installed     rpm-4.8.0-59.el6.x86_64                          @base
    Installed     yum-3.2.29-81.el6.centos.0.1.noarch              @updates
    Installed     yum-plugin-fastestmirror-1.1.30-42.el6_10.noarch @updates
Packages Altered:
    Updated holland-1.1.10-1.el6.noarch           @epel
    Update          1.1.13-1.el6.noarch           @epel
    Updated holland-common-1.1.10-1.el6.noarch    @epel
    Update                 1.1.13-1.el6.noarch    @epel
    Updated holland-mysql-1.1.10-1.el6.noarch     @epel
    Update                1.1.13-1.el6.noarch     @epel
    Updated holland-mysqldump-1.1.10-1.el6.noarch @epel
    Update                    1.1.13-1.el6.noarch @epel
-------------------------------------------------------------------------------
Transaction ID : 456
Begin time     : Wed Jan 30 04:39:37 2019
Begin rpmdb    : 425:984ba9fa137990535d21bf60f74ee4547211fa38
End time       :                           (0 seconds)
End rpmdb      : 425:9f5b633da0ec8ac2d55eaa5bd946e76c60bf5dfb
User           : root <root>
Return-Code    : Success
Command Line   : -e 0 -d 0 -y shell /etc/yum/yum-daily.yum
Additional non-default information stored: 1
Transaction performed with:
    Installed     rpm-4.8.0-59.el6.x86_64                          @base
    Installed     yum-3.2.29-81.el6.centos.0.1.noarch              @updates
    Installed     yum-plugin-fastestmirror-1.1.30-42.el6_10.noarch @updates
Packages Altered:
    Updated holland-1.1.9-1.el6.noarch            @epel
    Update          1.1.10-1.el6.noarch           @epel
    Updated holland-common-1.1.9-1.el6.noarch     @epel
    Update                 1.1.10-1.el6.noarch    @epel
    Updated holland-mysql-1.1.9-1.el6.noarch      @epel
    Update                1.1.10-1.el6.noarch     @epel
    Updated holland-mysqldump-1.1.9-1.el6.noarch  @epel
    Update                    1.1.10-1.el6.noarch @epel
-------------------------------------------------------------------------------
Transaction ID : 453
Begin time     : Thu Jan  3 04:00:43 2019
Begin rpmdb    : 424:2b20598998d49578f6f7fe7c825b97f0b2bd908e
End time       :            04:00:44 2019 (1 seconds)
End rpmdb      : 425:a5f6224fce5635e25ad7dc137876b174b354c59b
User           : root <root>
Return-Code    : Success
Command Line   : -e 0 -d 0 -y shell /etc/yum/yum-daily.yum
Additional non-default information stored: 1
Transaction performed with:
    Installed     rpm-4.8.0-59.el6.x86_64                          @base
    Installed     yum-3.2.29-81.el6.centos.0.1.noarch              @updates
    Installed     yum-metadata-parser-1.1.2-16.el6.x86_64          @anaconda-CentOS-201311272149.x86_64/6.5
    Installed     yum-plugin-fastestmirror-1.1.30-42.el6_10.noarch @updates
Packages Altered:
    Updated     holland-1.1.8-2.el6.noarch           @epel
    Update              1.1.9-1.el6.noarch           @epel
    Updated     holland-common-1.1.8-2.el6.noarch    @epel
    Update                     1.1.9-1.el6.noarch    @epel
    Updated     holland-mysql-1.1.8-2.el6.noarch     @epel
    Update                    1.1.9-1.el6.noarch     @epel
    Updated     holland-mysqldump-1.1.8-2.el6.noarch @epel
    Update                        1.1.9-1.el6.noarch @epel
    Dep-Install python2-mock-1.0.1-10.el6.noarch     @epel
-------------------------------------------------------------------------------
Transaction ID : 446
Begin time     : Mon Oct 15 03:18:13 2018
Begin rpmdb    : 424:5fd76904af89c45c6a3183be06ecd726c4c753c5
End time       :            03:18:14 2018 (1 seconds)
End rpmdb      : 424:374e28bd1e89d62d4477818ee13ac843c6fed785
User           : root <root>
Return-Code    : Success
Command Line   : -e 0 -d 0 -y shell /etc/yum/yum-daily.yum
Additional non-default information stored: 1
Transaction performed with:
    Installed     rpm-4.8.0-59.el6.x86_64                          @base
    Installed     yum-3.2.29-81.el6.centos.0.1.noarch              @updates
    Installed     yum-metadata-parser-1.1.2-16.el6.x86_64          @anaconda-CentOS-201311272149.x86_64/6.5
    Installed     yum-plugin-fastestmirror-1.1.30-42.el6_10.noarch @updates
Packages Altered:
    Updated holland-1.1.7-1.el6.noarch           @epel
    Update          1.1.8-2.el6.noarch           @epel
    Updated holland-common-1.1.7-1.el6.noarch    @epel
    Update                 1.1.8-2.el6.noarch    @epel
    Updated holland-mysql-1.1.7-1.el6.noarch     @epel
    Update                1.1.8-2.el6.noarch     @epel
    Updated holland-mysqldump-1.1.7-1.el6.noarch @epel
    Update                    1.1.8-2.el6.noarch @epel
-------------------------------------------------------------------------------
Transaction ID : 441
Begin time     : Sat Oct  6 03:47:13 2018
Begin rpmdb    : 423:8d308fac6d94eefa27893db2dc30ec48fa7e83da
End time       :                          (0 seconds)
End rpmdb      : 423:c948eef007c112616f3122d4d1bf34e8565f7baa
User           : root <root>
Return-Code    : Success
Command Line   : -e 0 -d 0 -y shell /etc/yum/yum-daily.yum
Additional non-default information stored: 1
Transaction performed with:
    Installed     rpm-4.8.0-59.el6.x86_64                          @base
    Updated       yum-3.2.29-81.el6.centos.noarch                  @base
    Installed     yum-metadata-parser-1.1.2-16.el6.x86_64          @anaconda-CentOS-201311272149.x86_64/6.5
    Installed     yum-plugin-fastestmirror-1.1.30-42.el6_10.noarch @updates
Packages Altered:
    Updated holland-1.1.5-1.el6.noarch           @epel
    Update          1.1.7-1.el6.noarch           @epel
    Updated holland-common-1.1.5-1.el6.noarch    @epel
    Update                 1.1.7-1.el6.noarch    @epel
    Updated holland-mysql-1.1.5-1.el6.noarch     @epel
    Update                1.1.7-1.el6.noarch     @epel
    Updated holland-mysqldump-1.1.5-1.el6.noarch @epel
    Update                    1.1.7-1.el6.noarch @epel
-------------------------------------------------------------------------------
Transaction ID : 440
Begin time     : Wed Oct  3 03:24:10 2018
Begin rpmdb    : 419:9b812b577b66f4670a2b7690765107d6a19843cd
End time       :            03:24:11 2018 (1 seconds)
End rpmdb      : 423:8d308fac6d94eefa27893db2dc30ec48fa7e83da
User           : root <root>
Return-Code    : Success
Command Line   : -e 0 -d 0 -y shell /etc/yum/yum-daily.yum
Additional non-default information stored: 1
Transaction performed with:
    Installed     rpm-4.8.0-59.el6.x86_64                          @base
    Updated       yum-3.2.29-81.el6.centos.noarch                  @base
    Installed     yum-metadata-parser-1.1.2-16.el6.x86_64          @anaconda-CentOS-201311272149.x86_64/6.5
    Installed     yum-plugin-fastestmirror-1.1.30-42.el6_10.noarch @updates
Packages Altered:
    Updated     holland-1.0.14-3.el6.noarch            @epel
    Update              1.1.5-1.el6.noarch             @epel
    Updated     holland-common-1.0.14-3.el6.noarch     @epel
    Update                     1.1.5-1.el6.noarch      @epel
    Updated     holland-mysql-1.0.14-3.el6.noarch      @epel
    Update                    1.1.5-1.el6.noarch       @epel
    Updated     holland-mysqldump-1.0.14-3.el6.noarch  @epel
    Update                        1.1.5-1.el6.noarch   @epel
    Dep-Install python-importlib-1.0.4-1.el6.noarch    @epel
    Dep-Install python2-future-0.16.0-11.el6.noarch    @epel
    Dep-Install python2-setuptools-0.6.10-0.el6.noarch @epel
    Dep-Install python2-six-1.9.0-0.el6.noarch         @epel
Scriptlet output:
   1 warning: /etc/holland/holland.conf created as /etc/holland/holland.conf.rpmnew
-------------------------------------------------------------------------------
Transaction ID : 368
Begin time     : Wed Mar  1 05:22:45 2017
Begin rpmdb    : 415:ebe5cfafd054e9cfdba53105c3219877ae6ce7c8
End time       :            05:22:46 2017 (1 seconds)
End rpmdb      : 416:4b67a230888833164b8fe3899e98d75c4dd36aca
User           : root <root>
Return-Code    : Success
Command Line   : -e 0 -d 0 -y shell /etc/yum/yum-daily.yum
Additional non-default information stored: 1
Transaction performed with:
    Updated       rpm-4.8.0-55.el6.x86_64                       @base
    Updated       yum-3.2.29-75.el6.centos.noarch               @updates
    Installed     yum-metadata-parser-1.1.2-16.el6.x86_64       @anaconda-CentOS-201311272149.x86_64/6.5
    Updated       yum-plugin-fastestmirror-1.1.30-37.el6.noarch @base
Packages Altered:
    Updated     holland-1.0.14-1.el6.noarch           @epel
    Update              1.0.14-3.el6.noarch           @epel
    Updated     holland-common-1.0.14-1.el6.noarch    @epel
    Update                     1.0.14-3.el6.noarch    @epel
    Dep-Install holland-mysql-1.0.14-3.el6.noarch     @epel
    Updated     holland-mysqldump-1.0.14-1.el6.noarch @epel
    Update                        1.0.14-3.el6.noarch @epel
-------------------------------------------------------------------------------
Transaction ID : 355
Begin time     : Thu Jan 19 04:21:18 2017
Begin rpmdb    : 414:0a482a8d5c9563f82c480ee30ca4dd16798a8ff6
End time       :                           (0 seconds)
End rpmdb      : 414:50da2654d6ef5a31e146b7778e6a42cbc2da928b
User           : root <root>
Return-Code    : Success
Command Line   : -e 0 -d 0 -y shell /etc/yum/yum-daily.yum
Additional non-default information stored: 1
Transaction performed with:
    Updated       rpm-4.8.0-55.el6.x86_64                       @base
    Updated       yum-3.2.29-75.el6.centos.noarch               @updates
    Installed     yum-metadata-parser-1.1.2-16.el6.x86_64       @anaconda-CentOS-201311272149.x86_64/6.5
    Updated       yum-plugin-fastestmirror-1.1.30-37.el6.noarch @base
Packages Altered:
    Updated holland-1.0.12-6.el6.noarch           @epel
    Update          1.0.14-1.el6.noarch           @epel
    Updated holland-common-1.0.12-6.el6.noarch    @epel
    Update                 1.0.14-1.el6.noarch    @epel
    Updated holland-mysqldump-1.0.12-6.el6.noarch @epel
    Update                    1.0.14-1.el6.noarch @epel
-------------------------------------------------------------------------------
Transaction ID : 322
Begin time     : Thu Aug 18 03:57:46 2016
Begin rpmdb    : 414:909a03835543a22cca0dd620f369a71d120e00ac
End time       :            03:57:47 2016 (1 seconds)
End rpmdb      : 414:0bb628715fa2bcb5e4cb563ec4af403e637525b0
User           : root <root>
Return-Code    : Success
Command Line   : -e 0 -d 0 -y shell /etc/yum/yum-daily.yum
Additional non-default information stored: 1
Transaction performed with:
    Updated       rpm-4.8.0-55.el6.x86_64                       @base
    Updated       yum-3.2.29-75.el6.centos.noarch               @updates
    Installed     yum-metadata-parser-1.1.2-16.el6.x86_64       @anaconda-CentOS-201311272149.x86_64/6.5
    Updated       yum-plugin-fastestmirror-1.1.30-37.el6.noarch @base
Packages Altered:
    Updated holland-1.0.12-4.el6.noarch           @epel
    Update          1.0.12-6.el6.noarch           @epel
    Updated holland-common-1.0.12-4.el6.noarch    @epel
    Update                 1.0.12-6.el6.noarch    @epel
    Updated holland-mysqldump-1.0.12-4.el6.noarch @epel
    Update                    1.0.12-6.el6.noarch @epel
-------------------------------------------------------------------------------
Transaction ID : 274
Begin time     : Sun Mar  6 04:10:38 2016
Begin rpmdb    : 408:a4b629199b610fa3c24835532d83beb136e8a668
End time       :                          (0 seconds)
End rpmdb      : 408:afeaf2fccbd27ad3ebd20eaf186fdbd70159bc7d
User           : root <root>
Return-Code    : Success
Command Line   : -e 0 -d 0 -y shell /etc/yum/yum-daily.yum
Additional non-default information stored: 1
Transaction performed with:
    Updated       rpm-4.8.0-47.el6.x86_64                       @base
    Updated       yum-3.2.29-69.el6.centos.noarch               @base
    Installed     yum-metadata-parser-1.1.2-16.el6.x86_64       @anaconda-CentOS-201311272149.x86_64/6.5
    Updated       yum-plugin-fastestmirror-1.1.30-30.el6.noarch @base
Packages Altered:
    Updated holland-1.0.12-3.el6.noarch           @epel
    Update          1.0.12-4.el6.noarch           @epel
    Updated holland-common-1.0.12-3.el6.noarch    @epel
    Update                 1.0.12-4.el6.noarch    @epel
    Updated holland-mysqldump-1.0.12-3.el6.noarch @epel
    Update                    1.0.12-4.el6.noarch @epel
-------------------------------------------------------------------------------
Transaction ID : 272
Begin time     : Wed Mar  2 04:24:40 2016
Begin rpmdb    : 408:5403ae2648d38d09853528d6110296f6cfa75a53
End time       :            04:24:42 2016 (2 seconds)
End rpmdb      : 408:c98ea4184b85ff074f2a535f722ceeeb5883c867
User           : root <root>
Return-Code    : Success
Command Line   : -e 0 -d 0 -y shell /etc/yum/yum-daily.yum
Additional non-default information stored: 1
Transaction performed with:
    Updated       rpm-4.8.0-47.el6.x86_64                       @base
    Updated       yum-3.2.29-69.el6.centos.noarch               @base
    Installed     yum-metadata-parser-1.1.2-16.el6.x86_64       @anaconda-CentOS-201311272149.x86_64/6.5
    Updated       yum-plugin-fastestmirror-1.1.30-30.el6.noarch @base
Packages Altered:
    Updated holland-1.0.10-3.el6.noarch            @epel
    Update          1.0.12-3.el6.noarch            @epel
    Updated holland-common-1.0.10-3.el6.noarch     @epel
    Update                 1.0.12-3.el6.noarch     @epel
    Updated holland-mysqldump-1.0.10-3.el6.noarch  @epel
    Update                    1.0.12-3.el6.noarch  @epel
    Updated openssl-1.0.1e-42.el6_7.2.i686         @updates
    Updated openssl-1.0.1e-42.el6_7.2.x86_64       @updates
    Update          1.0.1e-42.el6_7.4.i686         @updates
    Update          1.0.1e-42.el6_7.4.x86_64       @updates
    Updated openssl-devel-1.0.1e-42.el6_7.2.x86_64 @updates
    Update                1.0.1e-42.el6_7.4.x86_64 @updates
-------------------------------------------------------------------------------
Transaction ID : 124
Begin time     : Wed Dec  3 03:43:40 2014
Begin rpmdb    : 387:8493a91012a8706126a37ad410eb7869772aac49
End time       :            03:43:53 2014 (13 seconds)
End rpmdb      : 387:540dd551802a93d0da0424880eed5adb168ef6f8
User           : root <root>
Return-Code    : Success
Command Line   : -e 0 -d 0 -y shell /etc/yum/yum-daily.yum
Additional non-default information stored: 1
Transaction performed with:
    Updated       rpm-4.8.0-37.el6.x86_64                       @anaconda-CentOS-201311272149.x86_64/6.5
    Updated       yum-3.2.29-60.el6.centos.noarch               @base
    Installed     yum-metadata-parser-1.1.2-16.el6.x86_64       @anaconda-CentOS-201311272149.x86_64/6.5
    Updated       yum-plugin-fastestmirror-1.1.30-30.el6.noarch @base
Packages Altered:
    Updated holland-1.0.10-1.el6.noarch                @epel
    Update          1.0.10-3.el6.noarch                @epel
    Updated holland-common-1.0.10-1.el6.noarch         @epel
    Update                 1.0.10-3.el6.noarch         @epel
    Updated holland-mysqldump-1.0.10-1.el6.noarch      @epel
    Update                    1.0.10-3.el6.noarch      @epel
    Updated mysql55-5.5.40-1.ius.centos6.x86_64        @ius
    Update          5.5.40-2.ius.centos6.x86_64        @ius
    Updated mysql55-bench-5.5.40-1.ius.centos6.x86_64  @ius
    Update                5.5.40-2.ius.centos6.x86_64  @ius
    Updated mysql55-devel-5.5.40-1.ius.centos6.x86_64  @ius
    Update                5.5.40-2.ius.centos6.x86_64  @ius
    Updated mysql55-libs-5.5.40-1.ius.centos6.x86_64   @ius
    Update               5.5.40-2.ius.centos6.x86_64   @ius
    Updated mysql55-server-5.5.40-1.ius.centos6.x86_64 @ius
    Update                 5.5.40-2.ius.centos6.x86_64 @ius
    Updated php54-5.4.34-1.ius.centos6.x86_64          @ius
    Update        5.4.35-1.ius.centos6.x86_64          @ius
    Updated php54-bcmath-5.4.34-1.ius.centos6.x86_64   @ius
    Update               5.4.35-1.ius.centos6.x86_64   @ius
    Updated php54-cli-5.4.34-1.ius.centos6.x86_64      @ius
    Update            5.4.35-1.ius.centos6.x86_64      @ius
    Updated php54-common-5.4.34-1.ius.centos6.x86_64   @ius
    Update               5.4.35-1.ius.centos6.x86_64   @ius
    Updated php54-devel-5.4.34-1.ius.centos6.x86_64    @ius
    Update              5.4.35-1.ius.centos6.x86_64    @ius
    Updated php54-gd-5.4.34-1.ius.centos6.x86_64       @ius
    Update           5.4.35-1.ius.centos6.x86_64       @ius
    Updated php54-mbstring-5.4.34-1.ius.centos6.x86_64 @ius
    Update                 5.4.35-1.ius.centos6.x86_64 @ius
    Updated php54-mcrypt-5.4.34-1.ius.centos6.x86_64   @ius
    Update               5.4.35-1.ius.centos6.x86_64   @ius
    Updated php54-mysql-5.4.34-1.ius.centos6.x86_64    @ius
    Update              5.4.35-1.ius.centos6.x86_64    @ius
    Updated php54-pdo-5.4.34-1.ius.centos6.x86_64      @ius
    Update            5.4.35-1.ius.centos6.x86_64      @ius
    Updated php54-tidy-5.4.34-1.ius.centos6.x86_64     @ius
    Update             5.4.35-1.ius.centos6.x86_64     @ius
    Updated php54-xml-5.4.34-1.ius.centos6.x86_64      @ius
    Update            5.4.35-1.ius.centos6.x86_64      @ius
-------------------------------------------------------------------------------
Transaction ID : 17
Begin time     : Fri Mar 21 09:19:18 2014
Begin rpmdb    : 337:86b74f2edf3b851c0aa2bcdfa1114509210036e5
End time       :            09:19:19 2014 (1 seconds)
End rpmdb      : 338:ec471ea45d5f1a2b223c9170994dffba04396e2c
User           : root <root>
Return-Code    : Success
Command Line   : -d0 -e0 -y install holland-1.0.10-1.el6
Transaction performed with:
    Updated       rpm-4.8.0-37.el6.x86_64                         @anaconda-CentOS-201311272149.x86_64/6.5
    Updated       yum-3.2.29-43.el6.centos.noarch                 @updates
    Installed     yum-metadata-parser-1.1.2-16.el6.x86_64         @anaconda-CentOS-201311272149.x86_64/6.5
    Updated       yum-plugin-fastestmirror-1.1.30-17.el6_5.noarch @updates
Packages Altered:
    Install holland-1.0.10-1.el6.noarch @epel
history info
```

**Comment by soulen3** [comment]
So this has been failing since holland was updated from 1.0 to 1.1.  That means it's probably an issue with the device's python environment. 

You can downgrade holland to 1.0.14, or trying fixing the environment. It's likely an issue with configobj. Make sure you have at least version 4.6.0 installed. You should be able to check what version is installed with one of the following commands:
` pip freeze |grep configobj`  or ` rpm -qa|grep configobj`

**Comment by tomldickson** [comment]
This is probably the cause, but I get two different answers from those commands:

```
root@mysql.production (.91) /etc/holland/backupsets # pip freeze | grep configobj
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
You are using pip version 7.1.0, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
configobj==5.0.1
root@mysql.production (.91) /etc/holland/backupsets # rpm -qa|grep configobj
python-configobj-4.6.0-3.el6.noarch
root@mysql.production (.91) /etc/holland/backupsets # 
```

**Comment by soulen3** [comment]
You could try the following, but it might mess up other python applications
`pip uninstall -y configobj ; yum reinstall -y  python-configobj python-six`

**Comment by tomldickson** [comment]
This seems to be working, thank you! Nothing else runs on this beast save mysql and holland, so I think we're good to go.
