### ISSUE TITLE
Add options to skip symlinks to oldest and newest

### ISSUE THREAD

**Issue by hexmode** [holland-backup/holland#337]
Running `holland pg` I get:
```
2021-08-18 15:40:16,729 PID-24785 [ERROR] Uncaught exception while running command 'holland purge': OSError(95, 'Operation not supported')
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/holland/core/command/command.py", line 126, in dispatch
    return self.run(self.optparser.prog, opts, *args)
  File "/usr/lib/python2.6/site-packages/holland/commands/purge.py", line 74, in run
    purge_backupset(backupset, opts.force, opts.all)
  File "/usr/lib/python2.6/site-packages/holland/commands/purge.py", line 144, in purge_backupset
    backupset.update_symlinks()
  File "/usr/lib/python2.6/site-packages/holland/core/spool.py", line 228, in update_symlinks
    os.symlink(oldest_path, oldest_link)
OSError: [Errno 95] Operation not supported
```

because I'm backing up to a CIFS network drive that doesn't support symlinks.

**Comment by hexmode** [comment]
tyvm @soulen3 !
